---
resources:
- name: resource-gcsstatics
  type: git
  source:
    #uri: https://git.greenwood.ng/charyorde/gcsstatics.git
    uri: https://github.com/charyorde/gcsstatics.git
    skip_ssl_verification: true

jobs:
- name: build-static
  plan:
  - {get: resource-gcsstatics, trigger: true}
  - task: build-rst
    file: resource-gcsstatics/ci/sphinx.yml
  - put: resource-gcsstatics
    params: file: content
    #- task: build-markdown
      #file: resource-gcsstatics/ci/markdown.yml
